### ISSUE TITLE
Add Chaos Monkey and Orchestrator to recovery testing

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-test-suite#27]
Recovery testing currently only covers Author-Dispatcher, Publish, and Publish-Dispatcher components.
Chaos Monkey and Orchestrator components need to be added to the recovery test suite.

**Comment by mbloch1986** [comment]
Implemented in inspec-aem-aws version 0.12.0
https://github.com/shinesolutions/inspec-aem-aws/blob/master/CHANGELOG.md#0120---2019-04-01
