### ISSUE TITLE
Update config make targets

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-test-suite#35]
The InSpec profiles we are using are having their own config files with a list of ressources to check. E.g. the aem-test-suite only copies the `aem-aws.yaml` file to the directory while for the other configuration files the user can't overwrite those per default and always relies on the default configurations. We need to allow the user to define their own config file e.g. `cw_alarms`.

**Comment by hoomaan-kh** [comment]
it is fixed by replacing cp with \cp .
