### ISSUE TITLE
Security test for Dispatcher cache flush

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-test-suite#6]
As per https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher-configuration.html#main-pars_title_19, it shouldn't be possible to invalidate Dispatcher cache.

The sample command on that article is:
`curl -H "CQ-Handle: /content" -H "CQ-Path: /content" http://yourhostname/dispatcher/invalidate.cache`
However, for our test, let's simulate it with ruby.

**Comment by ibi456** [comment]
PR #7
